// ─────────────────────────────────────────────────────────────
// BANCO DE PREGUNTAS MODO DEMO
// 40-50 preguntas por tema, formato compatible con generarReto
// ─────────────────────────────────────────────────────────────

export const TEMAS_DEMO = [
  { id: 'cultura',     label: 'Cultura General', icono: '🌍', color: '#00FFFF' },
  { id: 'ciencia',     label: 'Ciencia',         icono: '🔬', color: '#00FF41' },
  { id: 'historia',    label: 'Historia',         icono: '🏛️', color: '#FFD700' },
  { id: 'curiosidades',label: 'Curiosidades',     icono: '🤔', color: '#FF00FF' },
  { id: 'matematicas', label: 'Matemáticas',      icono: '🔢', color: '#FF6600' },
  { id: 'naturaleza',  label: 'Naturaleza',       icono: '🌿', color: '#00FF88' },
];

const BANCO = {
  cultura: [
    { p:'¿Cuál es el país más grande del mundo?', c:'Rusia', f:['China','Canadá','Brasil'] },
    { p:'¿Cuántos continentes hay en el mundo?', c:'7', f:['5','6','8'] },
    { p:'¿Cuál es el idioma más hablado del mundo?', c:'Mandarin', f:['Inglés','Español','Hindi'] },
    { p:'¿En qué continente está Egipto?', c:'África', f:['Asia','Europa','América'] },
    { p:'¿Cuál es la capital de Francia?', c:'París', f:['Lyon','Marsella','Burdeos'] },
    { p:'¿Cuántos países hay en América Latina?', c:'20', f:['15','18','25'] },
    { p:'¿Cuál es el océano más grande?', c:'Pacífico', f:['Atlántico','Índico','Ártico'] },
    { p:'¿En qué país está la Torre Eiffel?', c:'Francia', f:['Italia','España','Bélgica'] },
    { p:'¿Cuál es el río más largo del mundo?', c:'Nilo', f:['Amazonas','Yangtze','Misisipi'] },
    { p:'¿Cuántos colores tiene el arcoíris?', c:'7', f:['5','6','8'] },
    { p:'¿Cuál es el planeta más grande del sistema solar?', c:'Júpiter', f:['Saturno','Neptuno','Urano'] },
    { p:'¿Qué moneda usa México?', c:'Peso', f:['Dólar','Euro','Bolívar'] },
    { p:'¿En qué ciudad está el Coliseo romano?', c:'Roma', f:['Atenas','Madrid','Lisboa'] },
    { p:'¿Cuál es el deporte más popular del mundo?', c:'Fútbol', f:['Baloncesto','Cricket','Tenis'] },
    { p:'¿Cuántos lados tiene un hexágono?', c:'6', f:['5','7','8'] },
    { p:'¿En qué continente está Brasil?', c:'América del Sur', f:['América Central','África','Asia'] },
    { p:'¿Cuál es el desierto más grande del mundo?', c:'Sahara', f:['Gobi','Atacama','Arábigo'] },
    { p:'¿Qué instrumento tiene 88 teclas?', c:'Piano', f:['Órgano','Acordeón','Arpa'] },
    { p:'¿Cuántos días tiene un año bisiesto?', c:'366', f:['365','367','364'] },
    { p:'¿Cuál es la capital de Japón?', c:'Tokio', f:['Osaka','Kioto','Hiroshima'] },
    { p:'¿Qué idioma se habla en Brasil?', c:'Portugués', f:['Español','Inglés','Francés'] },
    { p:'¿Cuántos planetas tiene el sistema solar?', c:'8', f:['9','7','10'] },
    { p:'¿En qué país está Machu Picchu?', c:'Perú', f:['Bolivia','Ecuador','Colombia'] },
    { p:'¿Cuál es el animal más rápido del mundo?', c:'Guepardo', f:['León','Halcón','Caballo'] },
    { p:'¿Cuántos huesos tiene el cuerpo humano adulto?', c:'206', f:['180','212','250'] },
    { p:'¿Qué gas respiramos principalmente?', c:'Nitrógeno', f:['Oxígeno','CO2','Argón'] },
    { p:'¿En qué país se inventó el papel?', c:'China', f:['Egipto','India','Japón'] },
    { p:'¿Cuál es el metal más abundante en la Tierra?', c:'Aluminio', f:['Hierro','Cobre','Zinc'] },
    { p:'¿Cuántos segundos tiene un minuto?', c:'60', f:['100','30','120'] },
    { p:'¿Qué país tiene más pirámides?', c:'Sudán', f:['Egipto','México','Perú'] },
    { p:'¿Cuántos litros de sangre tiene un adulto?', c:'5 litros', f:['3 litros','8 litros','10 litros'] },
    { p:'¿Cuál es la ciudad más poblada del mundo?', c:'Tokio', f:['Shanghái','Ciudad de México','Delhi'] },
    { p:'¿Qué país tiene más lagos del mundo?', c:'Canadá', f:['Rusia','Brasil','EE.UU.'] },
    { p:'¿Cuántas estrellas tiene la bandera de EE.UU.?', c:'50', f:['48','52','45'] },
    { p:'¿En qué año llegó el hombre a la Luna?', c:'1969', f:['1965','1972','1971'] },
    { p:'¿Cuál es el idioma oficial de Australia?', c:'Inglés', f:['Australiano','Aborigen','Francés'] },
    { p:'¿Cuántos metros mide un kilómetro?', c:'1000', f:['100','500','2000'] },
    { p:'¿Qué pintor pintó la Mona Lisa?', c:'Leonardo da Vinci', f:['Miguel Ángel','Rafael','Botticelli'] },
    { p:'¿Cuántas horas tiene un día?', c:'24', f:['12','36','48'] },
    { p:'¿En qué continente está Australia?', c:'Oceanía', f:['Asia','América','África'] },
  ],

  ciencia: [
    { p:'¿Cuál es la fórmula química del agua?', c:'H₂O', f:['CO₂','NaCl','O₂'] },
    { p:'¿Qué planeta es conocido como el planeta rojo?', c:'Marte', f:['Venus','Júpiter','Saturno'] },
    { p:'¿Cuántos elementos tiene la tabla periódica?', c:'118', f:['100','92','120'] },
    { p:'¿Qué científico propuso la Teoría de la Relatividad?', c:'Einstein', f:['Newton','Hawking','Bohr'] },
    { p:'¿A qué velocidad viaja la luz?', c:'300,000 km/s', f:['150,000 km/s','500,000 km/s','1,000 km/s'] },
    { p:'¿Cuál es el símbolo del oro en la tabla periódica?', c:'Au', f:['Go','Or','Ag'] },
    { p:'¿Qué orgánulo produce energía en la célula?', c:'Mitocondria', f:['Núcleo','Ribosoma','Vacuola'] },
    { p:'¿Cuál es el hueso más largo del cuerpo?', c:'Fémur', f:['Tibia','Húmero','Radio'] },
    { p:'¿Qué planeta tiene los anillos más visibles?', c:'Saturno', f:['Júpiter','Urano','Neptuno'] },
    { p:'¿Cuántos cromosomas tiene una célula humana?', c:'46', f:['23','48','44'] },
    { p:'¿Qué gas produce la fotosíntesis?', c:'Oxígeno', f:['CO₂','Nitrógeno','Hidrógeno'] },
    { p:'¿Cuál es el elemento más ligero?', c:'Hidrógeno', f:['Helio','Litio','Berilio'] },
    { p:'¿Qué fuerza mantiene los planetas en órbita?', c:'Gravedad', f:['Magnetismo','Fricción','Electricidad'] },
    { p:'¿Cuál es el punto de ebullición del agua?', c:'100°C', f:['80°C','120°C','90°C'] },
    { p:'¿Qué vitamina produce el sol en la piel?', c:'Vitamina D', f:['Vitamina C','Vitamina A','Vitamina B'] },
    { p:'¿Cuántos hemisferios cerebrales tiene el ser humano?', c:'2', f:['3','4','1'] },
    { p:'¿Qué es el ADN?', c:'Ácido desoxirribonucleico', f:['Ácido ribonucleico','Proteína','Carbohidrato'] },
    { p:'¿A qué temperatura el agua se convierte en hielo?', c:'0°C', f:['4°C','-10°C','2°C'] },
    { p:'¿Cuál es el metal más conductor de electricidad?', c:'Plata', f:['Cobre','Oro','Aluminio'] },
    { p:'¿Qué tipo de energía produce un panel solar?', c:'Eléctrica', f:['Térmica','Mecánica','Química'] },
    { p:'¿Cuántas dimensiones tiene el espacio-tiempo?', c:'4', f:['3','5','6'] },
    { p:'¿Qué invento se atribuye a Thomas Edison?', c:'Bombilla', f:['Teléfono','Radio','Televisión'] },
    { p:'¿Cuál es el órgano más grande del cuerpo?', c:'Piel', f:['Hígado','Intestino','Pulmón'] },
    { p:'¿Qué planeta está más cerca del Sol?', c:'Mercurio', f:['Venus','Marte','Tierra'] },
    { p:'¿Cuántas capas tiene la atmósfera terrestre?', c:'5', f:['3','4','7'] },
    { p:'¿Qué partícula tiene carga negativa?', c:'Electrón', f:['Protón','Neutrón','Quark'] },
    { p:'¿Cuál es el pH del agua pura?', c:'7', f:['5','9','6'] },
    { p:'¿Qué científico descubrió la penicilina?', c:'Fleming', f:['Pasteur','Koch','Darwin'] },
    { p:'¿Cuánto tarda la Tierra en girar sobre su eje?', c:'24 horas', f:['12 horas','48 horas','36 horas'] },
    { p:'¿Qué es la fotosíntesis?', c:'Proceso de producir alimento con luz solar', f:['Respiración celular','Digestión de minerales','División celular'] },
    { p:'¿Cuál es el número atómico del carbono?', c:'6', f:['8','12','4'] },
    { p:'¿Qué onda viaja más rápido en el espacio?', c:'Luz', f:['Sonido','Radio','Ultrasonido'] },
    { p:'¿Cuántos tipos de ondas sísmicas existen?', c:'3', f:['2','4','5'] },
    { p:'¿Qué animal tiene el corazón más grande?', c:'Ballena azul', f:['Elefante','Jirafa','Hipopótamo'] },
    { p:'¿Cuál es el símbolo del oxígeno?', c:'O', f:['Ox','Om','Oz'] },
    { p:'¿Qué planeta tarda más en orbitar el Sol?', c:'Neptuno', f:['Urano','Saturno','Júpiter'] },
    { p:'¿Cuántos sentidos tiene el ser humano?', c:'5', f:['4','6','7'] },
    { p:'¿Qué tipo de roca forma los volcanes?', c:'Ígnea', f:['Sedimentaria','Metamórfica','Calcárea'] },
    { p:'¿Cuál es la partícula más pequeña del átomo?', c:'Quark', f:['Electrón','Protón','Neutrón'] },
    { p:'¿Qué produce el efecto invernadero?', c:'CO₂ y otros gases', f:['Luz solar','Viento','Agua'] },
  ],

  historia: [
    { p:'¿En qué año comenzó la Primera Guerra Mundial?', c:'1914', f:['1918','1910','1916'] },
    { p:'¿Quién fue el primer presidente de México?', c:'Guadalupe Victoria', f:['Benito Juárez','Miguel Hidalgo','Agustín de Iturbide'] },
    { p:'¿En qué año cayó el Muro de Berlín?', c:'1989', f:['1991','1985','1987'] },
    { p:'¿Quién escribió el Quijote?', c:'Miguel de Cervantes', f:['Lope de Vega','Quevedo','Calderón'] },
    { p:'¿En qué año llegó Colón a América?', c:'1492', f:['1498','1502','1489'] },
    { p:'¿Qué civilización construyó las pirámides de Giza?', c:'Egipcios', f:['Mayas','Aztecas','Griegos'] },
    { p:'¿En qué año terminó la Segunda Guerra Mundial?', c:'1945', f:['1943','1947','1944'] },
    { p:'¿Quién fue Napoleón Bonaparte?', c:'Emperador de Francia', f:['Rey de España','Zar de Rusia','Faraón de Egipto'] },
    { p:'¿Dónde se firmó la Independencia de México?', c:'Chilpancingo', f:['Ciudad de México','Dolores','Querétaro'] },
    { p:'¿Quién fue el último faraón de Egipto?', c:'Cleopatra', f:['Ramsés II','Tutankamón','Nefertiti'] },
    { p:'¿En qué año se fundó la ONU?', c:'1945', f:['1950','1940','1948'] },
    { p:'¿Quién fue Simón Bolívar?', c:'Libertador de América del Sur', f:['Conquistador español','Rey de Colombia','Presidente de México'] },
    { p:'¿En qué siglo ocurrió la Revolución Francesa?', c:'Siglo XVIII', f:['Siglo XVII','Siglo XIX','Siglo XVI'] },
    { p:'¿Qué Imperio dominó Europa en el siglo I?', c:'Romano', f:['Griego','Persa','Mongol'] },
    { p:'¿En qué año inició la Revolución Mexicana?', c:'1910', f:['1905','1915','1920'] },
    { p:'¿Quién fue el primer astronauta en el espacio?', c:'Yuri Gagarin', f:['Neil Armstrong','Buzz Aldrin','Alan Shepard'] },
    { p:'¿En qué ciudad se firmó la Paz de Westfalia?', c:'Münster', f:['Berlín','París','Viena'] },
    { p:'¿Cuál fue la primera civilización de Mesoamérica?', c:'Olmeca', f:['Maya','Azteca','Tolteca'] },
    { p:'¿Quién conquistó el Imperio Azteca?', c:'Hernán Cortés', f:['Francisco Pizarro','Diego de Almagro','Vasco de Gama'] },
    { p:'¿En qué año nació Benito Juárez?', c:'1806', f:['1810','1800','1820'] },
    { p:'¿Qué país inició la Revolución Industrial?', c:'Inglaterra', f:['Francia','Alemania','EE.UU.'] },
    { p:'¿Quién fue Abraham Lincoln?', c:'Presidente de EE.UU.', f:['General confederado','Rey de Inglaterra','Inventor'] },
    { p:'¿En qué año se inventó la imprenta?', c:'1450', f:['1300','1500','1600'] },
    { p:'¿Qué cultura construyó Chichen Itzá?', c:'Maya', f:['Azteca','Olmeca','Tolteca'] },
    { p:'¿En qué año murió Cleopatra?', c:'30 a.C.', f:['69 a.C.','10 d.C.','50 a.C.'] },
    { p:'¿Quién descubrió Australia?', c:'James Cook', f:['Vasco de Gama','Magallanes','Colón'] },
    { p:'¿En qué siglo vivió Alejandro Magno?', c:'Siglo IV a.C.', f:['Siglo III a.C.','Siglo V a.C.','Siglo II a.C.'] },
    { p:'¿Qué país lanzó la bomba atómica en 1945?', c:'EE.UU.', f:['URSS','Reino Unido','Alemania'] },
    { p:'¿Quién fue el primer Papa de la historia?', c:'San Pedro', f:['San Pablo','San Juan','San Marcos'] },
    { p:'¿En qué año se firmó la Constitución de México?', c:'1917', f:['1910','1821','1857'] },
    { p:'¿Qué civilización creó el calendario más preciso?', c:'Maya', f:['Egipcia','Griega','Romana'] },
    { p:'¿Quién fue Moctezuma?', c:'Emperador Azteca', f:['Rey Maya','Conquistador español','Faraón'] },
    { p:'¿En qué año se descubrió América oficialmente?', c:'1492', f:['1500','1488','1502'] },
    { p:'¿Quién fue Gandhi?', c:'Líder independentista de India', f:['Presidente de India','Rey de India','General británico'] },
    { p:'¿En qué año nació Jesucristo?', c:'Año 0', f:['100 d.C.','33 a.C.','50 d.C.'] },
    { p:'¿Qué construcción conecta el Mediterráneo con el Mar Rojo?', c:'Canal de Suez', f:['Canal de Panamá','Estrecho de Gibraltar','Canal de Corinto'] },
    { p:'¿Quién escribió El Capital?', c:'Karl Marx', f:['Lenin','Engels','Trotski'] },
    { p:'¿En qué año se abolió la esclavitud en EE.UU.?', c:'1865', f:['1850','1880','1870'] },
    { p:'¿Qué civilización inventó el álgebra?', c:'Árabe', f:['Griega','Romana','China'] },
    { p:'¿En qué continente nació el ser humano?', c:'África', f:['Asia','Europa','América'] },
  ],

  curiosidades: [
    { p:'¿Cuántos corazones tiene un pulpo?', c:'3', f:['1','2','4'] },
    { p:'¿Qué animal no puede saltar?', c:'Elefante', f:['Hipopótamo','Rinoceronte','Cocodrilo'] },
    { p:'¿Cuánto tiempo vive un día un mosquito macho?', c:'10 días', f:['1 día','30 días','1 semana'] },
    { p:'¿De qué color es la sangre de los pulpos?', c:'Azul', f:['Roja','Verde','Amarilla'] },
    { p:'¿Cuántas veces por día parpadea un humano?', c:'15,000', f:['5,000','30,000','1,000'] },
    { p:'¿Qué animal duerme de pie?', c:'Caballo', f:['Vaca','Camello','Cebra'] },
    { p:'¿Cuánto tiempo puede vivir un escorpión sin comer?', c:'1 año', f:['1 mes','6 meses','2 años'] },
    { p:'¿Qué fruta tiene más vitamina C que una naranja?', c:'Guayaba', f:['Limón','Fresa','Kiwi'] },
    { p:'¿Cuántos músculos usa el ser humano para sonreír?', c:'17', f:['43','5','10'] },
    { p:'¿Qué animal tiene huellas idénticas a las humanas?', c:'Koala', f:['Chimpancé','Gorila','Oso'] },
    { p:'¿Cuántos idiomas hay en el mundo aproximadamente?', c:'7,000', f:['3,000','500','10,000'] },
    { p:'¿Qué país consume más chocolate per cápita?', c:'Suiza', f:['Bélgica','Alemania','EE.UU.'] },
    { p:'¿Cuántas abejas viven en una colmena?', c:'50,000', f:['1,000','100,000','500'] },
    { p:'¿De qué están hechas las uñas humanas?', c:'Queratina', f:['Calcio','Colágeno','Proteína'] },
    { p:'¿Qué animal puede regenerar su corazón?', c:'Pez cebra', f:['Salamandra','Estrella de mar','Lombriz'] },
    { p:'¿Cuánto pesa el cerebro humano?', c:'1.4 kg', f:['3 kg','0.5 kg','2 kg'] },
    { p:'¿Qué porcentaje del planeta es agua?', c:'71%', f:['50%','90%','60%'] },
    { p:'¿Cuántos dientes tiene un adulto humano?', c:'32', f:['28','36','30'] },
    { p:'¿Qué animal tiene la lengua más larga en relación a su cuerpo?', c:'Camaleón', f:['Oso hormiguero','Rana','Serpiente'] },
    { p:'¿Cuántos huesos tiene un bebé al nacer?', c:'270', f:['206','350','180'] },
    { p:'¿Qué fruta se llama también "pera de aguacate"?', c:'Aguacate', f:['Mango','Papaya','Guanábana'] },
    { p:'¿Cuánto tiempo tarda la luz del Sol en llegar a la Tierra?', c:'8 minutos', f:['1 segundo','1 hora','24 horas'] },
    { p:'¿Qué mamífero vuela?', c:'Murciélago', f:['Ardilla voladora','Zarigüeya','Lemur'] },
    { p:'¿Cuántas veces puede latir el corazón humano en un minuto?', c:'60-100', f:['30-50','150-200','10-20'] },
    { p:'¿Qué país tiene más volcanes activos?', c:'Indonesia', f:['Japón','México','Italia'] },
    { p:'¿Cuántos colores puede distinguir el ojo humano?', c:'10 millones', f:['1,000','100,000','1 millón'] },
    { p:'¿Qué porcentaje del cuerpo humano es agua?', c:'60%', f:['30%','90%','45%'] },
    { p:'¿Cuánto mide la uña humana en un mes?', c:'3mm', f:['1cm','5mm','1mm'] },
    { p:'¿Qué animal tiene más dientes?', c:'Caracol', f:['Tiburón','Cocodrilo','Delfín'] },
    { p:'¿Cuántas neuronas tiene el cerebro humano?', c:'86 mil millones', f:['1 millón','1 billón','100 millones'] },
    { p:'¿De dónde viene el chocolate?', c:'Cacao', f:['Café','Vainilla','Caña de azúcar'] },
    { p:'¿Qué país inventó el papel moneda?', c:'China', f:['EE.UU.','Roma','Grecia'] },
    { p:'¿Cuántas patas tiene una araña?', c:'8', f:['6','10','12'] },
    { p:'¿Qué sentido tiene mayor alcance?', c:'Vista', f:['Olfato','Oído','Tacto'] },
    { p:'¿Cuánto tiempo vive una mariposa adulta?', c:'2-4 semanas', f:['1 año','1 día','6 meses'] },
    { p:'¿Qué animal tiene el embarazo más largo?', c:'Elefante (22 meses)', f:['Ballena (12 meses)','Jirafa (15 meses)','Rinoceronte (18 meses)'] },
    { p:'¿Cuántos km² tiene la selva amazónica?', c:'5.5 millones km²', f:['1 millón km²','10 millones km²','3 millones km²'] },
    { p:'¿Qué animal tiene el cuello más largo?', c:'Jirafa', f:['Cisne','Avestruz','Camello'] },
    { p:'¿Cuántos litros de saliva produce un humano al día?', c:'1.5 litros', f:['0.1 litros','5 litros','10 litros'] },
    { p:'¿Qué país tiene más especies de aves?', c:'Colombia', f:['Brasil','Ecuador','Perú'] },
  ],

  matematicas: [
    { p:'¿Cuánto es 7 × 8?', c:'56', f:['54','58','48'] },
    { p:'¿Cuál es la raíz cuadrada de 144?', c:'12', f:['14','11','13'] },
    { p:'¿Cuánto es 15% de 200?', c:'30', f:['20','25','35'] },
    { p:'¿Qué número es primo?', c:'17', f:['15','21','25'] },
    { p:'¿Cuánto es 2⁸?', c:'256', f:['128','512','64'] },
    { p:'¿Cuál es el valor de π aproximadamente?', c:'3.14159', f:['2.71828','1.61803','3.41159'] },
    { p:'¿Cuánto es 1/4 + 1/2?', c:'3/4', f:['1/2','1/6','2/4'] },
    { p:'¿Cuántos grados tiene un triángulo?', c:'180°', f:['90°','360°','270°'] },
    { p:'¿Qué es un número impar?', c:'No divisible entre 2', f:['Divisible entre 2','Negativo','Primo'] },
    { p:'¿Cuánto es 12² - 100?', c:'44', f:['40','48','34'] },
    { p:'¿Cuántos lados tiene un octágono?', c:'8', f:['6','10','7'] },
    { p:'¿Cuál es el MCD de 12 y 18?', c:'6', f:['3','4','9'] },
    { p:'¿Cuánto es 0.5 × 0.5?', c:'0.25', f:['0.5','1','0.1'] },
    { p:'¿Qué es la mediana?', c:'Valor central de un conjunto', f:['Promedio','Valor más frecuente','Suma total'] },
    { p:'¿Cuánto es 3³?', c:'27', f:['9','18','36'] },
    { p:'¿Cuántos ángulos rectos tiene un cuadrado?', c:'4', f:['2','3','8'] },
    { p:'¿Cuál es la fórmula del área de un círculo?', c:'π r²', f:['2πr','πd','r²'] },
    { p:'¿Cuánto es 1,000 ÷ 25?', c:'40', f:['35','45','50'] },
    { p:'¿Qué número viene después de 999?', c:'1,000', f:['1,001','9,999','998'] },
    { p:'¿Cuánto es 30% de 300?', c:'90', f:['60','30','120'] },
    { p:'¿Cuál es el siguiente número de la serie: 2, 4, 8, 16?', c:'32', f:['18','24','20'] },
    { p:'¿Cuántos minutos hay en 3 horas?', c:'180', f:['120','240','150'] },
    { p:'¿Qué es el perímetro?', c:'Suma de todos los lados', f:['Área del interior','Volumen','Diagonal'] },
    { p:'¿Cuánto es -5 × -3?', c:'15', f:['-15','8','-8'] },
    { p:'¿Cuántos cm tiene un metro?', c:'100', f:['10','1000','50'] },
    { p:'¿Cuál es el área de un cuadrado de lado 5?', c:'25', f:['20','10','30'] },
    { p:'¿Qué es un ángulo obtuso?', c:'Mayor de 90° y menor de 180°', f:['Menor de 90°','Exactamente 90°','Mayor de 180°'] },
    { p:'¿Cuánto es 7!?', c:'5040', f:['720','40320','2520'] },
    { p:'¿Cuál es la raíz cuadrada de 225?', c:'15', f:['12','18','14'] },
    { p:'¿Cuánto es 2/3 de 90?', c:'60', f:['30','45','75'] },
    { p:'¿Qué es un número irracional?', c:'No se puede expresar como fracción', f:['Número negativo','Número primo','Número par'] },
    { p:'¿Cuántos ejes de simetría tiene un círculo?', c:'Infinitos', f:['1','4','0'] },
    { p:'¿Cuánto es 1000 × 0.001?', c:'1', f:['0.1','10','100'] },
    { p:'¿Cuántos vértices tiene un cubo?', c:'8', f:['6','12','4'] },
    { p:'¿Qué es la moda estadística?', c:'El valor que más se repite', f:['El promedio','El valor central','La diferencia mayor'] },
    { p:'¿Cuánto es 45 + 37 - 12?', c:'70', f:['80','60','75'] },
    { p:'¿Qué fracción equivale a 0.75?', c:'3/4', f:['1/4','2/3','7/5'] },
    { p:'¿Cuánto es 4 × 4 × 4?', c:'64', f:['48','32','96'] },
    { p:'¿Cuántos lados tiene un dodecágono?', c:'12', f:['10','14','8'] },
    { p:'¿Cuál es el volumen de un cubo de lado 3?', c:'27', f:['9','18','81'] },
  ],

  naturaleza: [
    { p:'¿Qué proceso usan las plantas para hacer su alimento?', c:'Fotosíntesis', f:['Respiración','Digestión','Fermentación'] },
    { p:'¿Cuál es el árbol más alto del mundo?', c:'Secuoya', f:['Eucalipto','Pino','Roble'] },
    { p:'¿Qué animal es el símbolo de la paz?', c:'Paloma', f:['Águila','Cisne','Gaviota'] },
    { p:'¿Cuántas capas tiene la Tierra?', c:'4', f:['3','5','6'] },
    { p:'¿Qué produce un volcán?', c:'Lava y ceniza', f:['Agua y gas','Hielo y vapor','Arena y roca'] },
    { p:'¿Cuál es el animal marino más grande?', c:'Ballena azul', f:['Tiburón blanco','Mantarraya','Calamar gigante'] },
    { p:'¿Qué tipo de roca forma los acantilados de cal?', c:'Caliza', f:['Granito','Basalto','Pizarra'] },
    { p:'¿Cuántos tipos de biomas hay en la Tierra?', c:'5 principales', f:['3','10','2'] },
    { p:'¿Qué es la biodiversidad?', c:'Variedad de seres vivos en un ecosistema', f:['Número de plantas','Cantidad de agua','Tipos de rocas'] },
    { p:'¿Cuál es el ecosistema más productivo?', c:'Arrecife de coral', f:['Desierto','Tundra','Pradera'] },
    { p:'¿Qué capa de la atmósfera nos protege del sol?', c:'Ozono', f:['Tropósfera','Mesósfera','Termósfera'] },
    { p:'¿Qué animal poliniza el 80% de las flores?', c:'Abeja', f:['Mariposa','Colibrí','Escarabajo'] },
    { p:'¿Cuánto tarda un árbol en crecer 1 metro?', c:'Depende de la especie', f:['Siempre 10 años','Exactamente 5 años','1 año siempre'] },
    { p:'¿Qué fenómeno causa las mareas?', c:'Gravedad de la Luna', f:['Viento','Rotación terrestre','Calor solar'] },
    { p:'¿Cuál es el río más caudaloso del mundo?', c:'Amazonas', f:['Nilo','Congo','Mississippi'] },
    { p:'¿Qué es la cadena alimentaria?', c:'Relación de quién come a quién', f:['Ciclo del agua','Fotosíntesis','Ciclo de rocas'] },
    { p:'¿Cuántos tipos de hongos existen aproximadamente?', c:'144,000', f:['1,000','500','10,000'] },
    { p:'¿Qué animal construye diques en los ríos?', c:'Castor', f:['Nutria','Cocodrilo','Hipopótamo'] },
    { p:'¿Cuál es la planta más grande del mundo?', c:'Secuoya gigante', f:['Roble','Baobab','Ceiba'] },
    { p:'¿Qué produce la aurora boreal?', c:'Partículas solares en la atmósfera', f:['Reflexión del hielo','Luz de la luna','Volcanes'] },
    { p:'¿Cuántos litros de agua hay en los océanos?', c:'1.335 quintillones de litros', f:['1 billón','1 trillón','1 millón de km³'] },
    { p:'¿Qué animal tiene mayor esperanza de vida?', c:'Tortuga de Galápagos', f:['Ballena','Elefante','Loro'] },
    { p:'¿Cuál es el mineral más duro de la naturaleza?', c:'Diamante', f:['Cuarzo','Granito','Rubí'] },
    { p:'¿Qué es un ecosistema?', c:'Comunidad de seres vivos y su entorno', f:['Solo las plantas de un área','Solo los animales','El suelo de una región'] },
    { p:'¿Cuántas especies de insectos existen?', c:'Más de 1 millón', f:['10,000','500,000','100,000'] },
    { p:'¿Qué tipo de energía produce el viento?', c:'Eólica', f:['Solar','Hidráulica','Geotérmica'] },
    { p:'¿Cuánto tarda el plástico en degradarse?', c:'400-1000 años', f:['10 años','100 años','50 años'] },
    { p:'¿Qué es la fotosíntesis?', c:'Proceso de hacer alimento con luz', f:['Respirar del sol','Comer tierra','Beber agua solar'] },
    { p:'¿Cuál es el bioma más extenso del mundo?', c:'Taiga', f:['Tundra','Selva tropical','Sabana'] },
    { p:'¿Qué produce el calentamiento global?', c:'Aumento de CO₂ y otros gases', f:['Más lluvia','Más oxígeno','Enfriamiento polar'] },
    { p:'¿Cuántas especies de aves existen?', c:'10,000', f:['1,000','50,000','5,000'] },
    { p:'¿Qué animal tiene la visión más aguda?', c:'Águila', f:['Halcón','Lechuza','Cóndor'] },
    { p:'¿Cuál es la flor más grande del mundo?', c:'Rafflesia', f:['Girasol','Loto','Orquídea'] },
    { p:'¿Qué mineral forma los huesos?', c:'Calcio y fósforo', f:['Hierro y zinc','Sodio y potasio','Magnesio y cloro'] },
    { p:'¿Cuántos años tarda un coral en crecer 1 cm?', c:'10 años', f:['1 año','100 años','1 mes'] },
    { p:'¿Qué es el permafrost?', c:'Suelo permanentemente congelado', f:['Glaciar marino','Capa de hielo ártico','Tundra desértica'] },
    { p:'¿Cuál es el veneno más potente del reino animal?', c:'Rana dardo venenosa', f:['Cobra','Escorpión','Medusa caja'] },
    { p:'¿Qué produce el sonido del trueno?', c:'Expansión rápida del aire por el rayo', f:['Nubes chocando','Viento fuerte','Agua en las nubes'] },
    { p:'¿Cuánto tiempo tarda el agua en evaporarse del océano?', c:'Variable según temperatura', f:['Siempre 24 horas','Exactamente 1 semana','Nunca se evapora'] },
    { p:'¿Qué % del agua de la Tierra es dulce?', c:'2.5%', f:['50%','10%','25%'] },
  ],
};

// ── Generador de reto para modo demo ─────────────────────────
export function generarRetoDemo(temaId) {
  const preguntas = BANCO[temaId];
  if (!preguntas || preguntas.length === 0) return null;

  const idx = Math.floor(Math.random() * preguntas.length);
  const q   = preguntas[idx];

  // Mezclar opciones
  const falsas = q.f.slice(0, 2).map(t => ({ texto: t, esCorrecto: false }));
  const correcta = { texto: q.c, esCorrecto: true };
  const opciones = [...falsas, correcta].sort(() => Math.random() - 0.5);

  return { pregunta: q.p, opciones };
}
